apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: domain.flows
spec:
  destination:
    namespace: flows
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      jsonnet: {}
      recurse: true
    path: release
    repoURL: >-
      ${REPO_URL}
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      
