apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  ${RELEASE_NAME}
  namespace:  ${NAMESPACE}
spec:
  project: ${PROJECT}
  source:
    chart: node-red
    repoURL: https://michaelkoch.github.io/charts
    targetRevision: 0.0.1
    helm:
      releaseName:  ${RELEASE_NAME}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ${NAMESPACE}